nodeLinker: pnp

# Enable loose mode for better compatibility with tools like Vite
pnpMode: loose

# Allow fallback to node_modules resolution when PnP fails
pnpFallbackMode: all

# Suppress specific peer dependency warnings that don't affect functionality
#
# YN0086 - cssstyle/postcss peer dependency warning:
# - cssstyle (used by jsdom for CSS parsing in tests) doesn't explicitly provide postcss
# - postcss is available globally in our project and works correctly with Tailwind CSS
# - This is a structural issue in the dependency graph, not a functional problem
# - The warning is safe to ignore as it doesn't impact builds, tests, or runtime behavior
logFilters:
  - code: YN0086
    text: "cssstyle@npm:5.3.1 doesn't provide postcss"
    level: discard
